version: "3.8"

services:
  # Dynamic Statamic site for content management
  statamic-dynamic:
    image: your-statamic-image:latest # You'll need to build this
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://cms.yourdomain.com
    volumes:
      - statamic-database:/app/database
      - statamic-assets:/app/public/assets
      - statamic-glide:/app/public/glide
      - static-output:/app/static
    secrets:
      - basic_auth_password
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.services.statamic-dynamic.loadbalancer.server.port=80
        # HTTP router (redirects to HTTPS)
        - traefik.http.routers.statamic-dynamic-http.rule=Host(`cms.yourdomain.com`)
        - traefik.http.routers.statamic-dynamic-http.entrypoints=web
        - traefik.http.routers.statamic-dynamic-http.middlewares=redirect-to-https
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        # HTTPS router
        - traefik.http.routers.statamic-dynamic-https.rule=Host(`cms.yourdomain.com`)
        - traefik.http.routers.statamic-dynamic-https.entrypoints=websecure
        - traefik.http.routers.statamic-dynamic-https.tls.certresolver=myresolver
        # Basic auth using Docker secret
        - traefik.http.middlewares.statamic-auth.basicauth.usersfile=/run/secrets/basic_auth_password
        - traefik.http.routers.statamic-dynamic-https.middlewares=statamic-auth@docker
        # Auto-update label for Gantry
        - auto-update=true

  # WordPress images nginx server
  wordpress-images:
    image: nginx:alpine
    volumes:
      - ./public/assets/wp-content:/usr/share/nginx/html/wp-content:ro
      - ./nginx-wp-content.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.services.wordpress-images.loadbalancer.server.port=80
        # High priority router for wp-content paths
        - traefik.http.routers.wordpress-images.rule=(Host(`yourdomain.com`) || Host(`www.yourdomain.com`)) && PathPrefix(`/wp-content`)
        - traefik.http.routers.wordpress-images.priority=100
        - traefik.http.routers.wordpress-images.tls.certresolver=letsencrypt

  # Static site nginx server
  statamic-static:
    image: nginx:alpine
    volumes:
      - static-output:/usr/share/nginx/html:ro
      - statamic-assets:/usr/share/nginx/html/assets:ro
      - statamic-glide:/usr/share/nginx/html/glide:ro
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.services.statamic-static.loadbalancer.server.port=80
        - traefik.http.routers.statamic-static.rule=Host(`yourdomain.com`) || Host(`www.yourdomain.com`)
        - traefik.http.routers.statamic-static.tls.certresolver=letsencrypt
        # Redirect www to non-www
        - traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www\.(.+)
        - traefik.http.middlewares.www-redirect.redirectregex.replacement=https://${1}
        - traefik.http.routers.statamic-static.middlewares=www-redirect@docker

volumes:
  statamic-database:
    driver: local
  statamic-assets:
    driver: local
  statamic-glide:
    driver: local
  static-output:
    driver: local

networks:
  traefik-public:
    external: true

secrets:
  basic_auth_password:
    external: true
